const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Json,
		C3.Plugins.BinaryData,
		C3.Plugins.LocalStorage,
		C3.Plugins.Spritefont2,
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Plugins.AJAX,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Behaviors.scrollto,
		C3.Behaviors.MoveTo,
		C3.Behaviors.Timer,
		C3.Plugins.Audio,
		C3.Behaviors.Follow,
		C3.Behaviors.EightDir,
		C3.Behaviors.Bullet,
		C3.Plugins.Arr,
		C3.Behaviors.Tween,
		C3.Behaviors.Rotate,
		C3.Behaviors.Pin,
		C3.Plugins.NinePatch,
		C3.Plugins.TiledBg,
		C3.Behaviors.Pathfinding,
		C3.Behaviors.bound,
		C3.Behaviors.solid,
		C3.Plugins.Particles,
		C3.Plugins.Tilemap,
		C3.Behaviors.Fade,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Behaviors.EightDir.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Mouse.Cnds.IsButtonDown,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.Particles.Acts.SetSpraying,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Particles.Acts.SetPos,
		C3.Behaviors.Timer.Cnds.IsTimerRunning,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.System.Exps.max,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Follow.Acts.FollowObject,
		C3.Behaviors.Follow.Acts.SetCustomPropertyValue,
		C3.Behaviors.Follow.Acts.StartFollowingCustomProperty,
		C3.Behaviors.Follow.Exps.DelayedCustomPropertyValue,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Behaviors.Timer.Exps.CurrentTime,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Exps.zeropad,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Spritefont2.Acts.SetDefaultColor,
		C3.Plugins.System.Exps.rgbex255,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Mouse.Acts.SetCursor2,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Sprite.Exps.PickedCount,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Arr.Exps.Height,
		C3.Plugins.TiledBg.Acts.SetPosToObject,
		C3.Plugins.TiledBg.Acts.MoveToTop,
		C3.Behaviors.Timer.Exps.NormalizedProgress,
		C3.Plugins.TiledBg.Acts.SetImageOffsetX,
		C3.Plugins.TiledBg.Exps.ImageOffsetX,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.System.Cnds.Repeat,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Exps.choose,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Audio.Acts.RemoveEffects,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.AddDelayEffect,
		C3.Behaviors.MoveTo.Cnds.OnArrived,
		C3.Behaviors.MoveTo.Cnds.OnHitSolid,
		C3.Behaviors.Tween.Acts.StopTweens,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.PickParent,
		C3.Behaviors.EightDir.Acts.SetMaxSpeed,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Arr.Cnds.IsEmpty,
		C3.Plugins.Arr.Cnds.CompareSize,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Plugins.Arr.Acts.Clear,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Exps.uppercase,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Behaviors.Timer.Acts.StopTimer,
		C3.Plugins.System.Acts.RecreateInitialObjects,
		C3.Plugins.Arr.Acts.Delete,
		C3.Behaviors.Follow.Acts.SetDelay,
		C3.Plugins.TiledBg.Acts.SetDefaultColor,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Behaviors.MoveTo.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.MoveForward,
		C3.Behaviors.MoveTo.Acts.SetMaxSpeed,
		C3.Behaviors.MoveTo.Acts.SetAcceleration,
		C3.Behaviors.MoveTo.Acts.SetDeceleration,
		C3.Behaviors.Pathfinding.Acts.FindPath,
		C3.Behaviors.Pathfinding.Cnds.OnPathFound,
		C3.Behaviors.MoveTo.Acts.MoveAlongPathfindingPath,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Sprite.Exps.ImageWidth,
		C3.Plugins.Sprite.Exps.ImageHeight,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.System.Acts.SetObjectTimescale,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.Sprite.Cnds.IsOnLayer,
		C3.Plugins.System.Acts.SortZOrderByInstVar,
		C3.Plugins.Tilemap.Cnds.CompareTileAt,
		C3.Plugins.Tilemap.Exps.TileToPositionX,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.AJAX.Acts.SetResponseBinary,
		C3.Plugins.Json.Acts.SetValue,
		C3.Plugins.AJAX.Acts.SetHeader,
		C3.Plugins.AJAX.Acts.Post,
		C3.Plugins.Json.Exps.ToCompactString,
		C3.Plugins.Json.Acts.SetJSON,
		C3.Plugins.BinaryData.Exps.GetText,
		C3.Plugins.BinaryData.Exps.ByteLength,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Cnds.OnFrameChanged,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.Sprite.Cnds.AngleWithin,
		C3.Plugins.Spritefont2.Exps.Y,
		C3.Plugins.System.Exps.len,
		C3.Plugins.Spritefont2.Acts.AppendText,
		C3.Plugins.System.Exps.time,
		C3.Plugins.System.Exps.mid,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Behaviors.Tween.Acts.StopAllTweens,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Behaviors.Sin.Acts.SetPhase,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.Json.Cnds.ForEach,
		C3.Plugins.Spritefont2.Acts.TypewriterText,
		C3.Plugins.Keyboard.Cnds.OnAnyKey,
		C3.Plugins.Spritefont2.Cnds.IsRunningTypewriterText,
		C3.Plugins.Spritefont2.Acts.TypewriterFinish,
		C3.Plugins.Spritefont2.Acts.SetInstanceVar,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Spritefont2.Cnds.OnTypewriterTextFinished,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Spritefont2.Cnds.IsOnScreen,
		C3.Plugins.System.Exps.left,
		C3.Plugins.System.Exps.find,
		C3.Plugins.Keyboard.Exps.TypedKey,
		C3.Plugins.Spritefont2.Exps.X,
		C3.Plugins.Spritefont2.Exps.TextWidth,
		C3.Plugins.Spritefont2.Exps.Height
	];
};
self.C3_JsPropNameTable = [
	{SubmitScoreJSON: 0},
	{SessionJson: 0},
	{ScoreBinaryData: 0},
	{ResponseJSON: 0},
	{LocalStorage: 0},
	{LeaderboardJSON: 0},
	{LeaderboardBinaryData: 0},
	{AuthenticationJSON: 0},
	{AuthenticationBinaryData: 0},
	{Type: 0},
	{LeaderBoardText: 0},
	{Medal: 0},
	{Sine: 0},
	{Sine2: 0},
	{Leaderboard: 0},
	{EnterCursor: 0},
	{EnterName: 0},
	{HowToPlay: 0},
	{TutorialText: 0},
	{AJAX: 0},
	{JSON: 0},
	{Keyboard: 0},
	{Mouse: 0},
	{ScrollTo: 0},
	{MoveTo: 0},
	{Timer: 0},
	{GameManager: 0},
	{Audio: 0},
	{DirX: 0},
	{DirY: 0},
	{MoveState: 0},
	{Name: 0},
	{SpecialState: 0},
	{FollowDelay: 0},
	{State: 0},
	{ShootAngle: 0},
	{KilledByEnemy: 0},
	{Active: 0},
	{Wave: 0},
	{Follow: 0},
	{PastPlayer: 0},
	{Description: 0},
	{"8Direction": 0},
	{Player: 0},
	{Order: 0},
	{Damage: 0},
	{Bullet: 0},
	{PlayerBullet: 0},
	{PlayerSprite: 0},
	{Characters: 0},
	{BulletShadow: 0},
	{Tween: 0},
	{SaveCharacter: 0},
	{Back: 0},
	{PlayerUID: 0},
	{Rotate: 0},
	{BoneProjectile: 0},
	{Pin: 0},
	{BoneShadow: 0},
	{WeaponHand: 0},
	{RosterArray: 0},
	{Grenade: 0},
	{GrenadeRadius: 0},
	{PlayerShadow: 0},
	{MuzzleFlash: 0},
	{AirstrikeRadius: 0},
	{BottleRadius: 0},
	{FlameBottle: 0},
	{CharacterDescription: 0},
	{Cursor: 0},
	{EnemiesLeft: 0},
	{TimerFont: 0},
	{TimeHud: 0},
	{EraName: 0},
	{Reference: 0},
	{Position: 0},
	{TitleButton: 0},
	{CharacterLeft: 0},
	{ScoreText: 0},
	{ChooseEra: 0},
	{CharacterText: 0},
	{PlayerDamageBar: 0},
	{PlayerHPBar: 0},
	{PlayerHUD: 0},
	{PlayerName: 0},
	{EnterScore: 0},
	{EnterNameText: 0},
	{EnemyIcon: 0},
	{SpecialBar: 0},
	{SpecialHUD: 0},
	{TimeParadox: 0},
	{AttackName: 0},
	{EraClear: 0},
	{HP: 0},
	{Pathfinding: 0},
	{Enemy: 0},
	{BoundToLayout: 0},
	{EnemyMarker: 0},
	{Crawler: 0},
	{BodyNum: 0},
	{BodyOrder: 0},
	{CrawlerSprite: 0},
	{EnemyBullet: 0},
	{FlyEnemy: 0},
	{FlyShadow: 0},
	{FlyTarget: 0},
	{Tick: 0},
	{TickShadow: 0},
	{TickTarget: 0},
	{EnemyBulletShadow: 0},
	{ChaserSprite: 0},
	{FeatureKreep: 0},
	{FeatureKreepLogo: 0},
	{IntroClockHand: 0},
	{GameLogo: 0},
	{IntroPortal: 0},
	{IntroStar: 0},
	{LogoBottom: 0},
	{LogoShine: 0},
	{SelectionBar: 0},
	{IntroImage: 0},
	{TypeText: 0},
	{IntroText: 0},
	{PrimalBackground: 0},
	{Solid: 0},
	{Box: 0},
	{ExampleBG: 0},
	{Portal: 0},
	{PortalParticles: 0},
	{SwitchEffect: 0},
	{LayerDarken: 0},
	{Tilemap: 0},
	{BoxOutline: 0},
	{ReferenceSprite: 0},
	{TiledBackground2: 0},
	{TransitionSprite: 0},
	{GameOver: 0},
	{GateButton: 0},
	{Gate: 0},
	{OpenButton: 0},
	{ShootOrb: 0},
	{Hourglass: 0},
	{HelpSign: 0},
	{ChaserOutline: 0},
	{NoGoZone: 0},
	{Fade: 0},
	{BulletHit: 0},
	{Explosion: 0},
	{ExplosionParticle: 0},
	{EnemyExplosion: 0},
	{RunParticles: 0},
	{Fire: 0},
	{PlayerCharacters: 0},
	{SortY: 0},
	{Enemies: 0},
	{CrawlerBodies: 0},
	{Score: 0},
	{PlayersLeft: 0},
	{PlayerHP: 0},
	{GameState: 0},
	{Perfect: 0},
	{CameraMode: 0},
	{SelectAge: 0},
	{SelectButton: 0},
	{TitleState: 0},
	{SelectPosition: 0},
	{PortalSpeed: 0},
	{IntroLine: 0}
];

self.InstanceType = {
	SubmitScoreJSON: class extends self.IJSONInstance {},
	SessionJson: class extends self.IJSONInstance {},
	ScoreBinaryData: class extends self.IBinaryDataInstance {},
	ResponseJSON: class extends self.IJSONInstance {},
	LocalStorage: class extends self.IInstance {},
	LeaderboardJSON: class extends self.IJSONInstance {},
	LeaderboardBinaryData: class extends self.IBinaryDataInstance {},
	AuthenticationJSON: class extends self.IJSONInstance {},
	AuthenticationBinaryData: class extends self.IBinaryDataInstance {},
	LeaderBoardText: class extends self.ISpriteFontInstance {},
	Medal: class extends self.ISpriteInstance {},
	Leaderboard: class extends self.ISpriteInstance {},
	EnterCursor: class extends self.ISpriteInstance {},
	EnterName: class extends self.ISpriteInstance {},
	HowToPlay: class extends self.ISpriteInstance {},
	TutorialText: class extends self.ISpriteFontInstance {},
	AJAX: class extends self.IInstance {},
	JSON: class extends self.IJSONInstance {},
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	GameManager: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	PastPlayer: class extends self.ISpriteInstance {},
	Player: class extends self.ISpriteInstance {},
	PlayerBullet: class extends self.ISpriteInstance {},
	PlayerSprite: class extends self.ISpriteInstance {},
	Characters: class extends self.IArrayInstance {},
	BulletShadow: class extends self.ISpriteInstance {},
	SaveCharacter: class extends self.ISpriteInstance {},
	BoneProjectile: class extends self.ISpriteInstance {},
	BoneShadow: class extends self.ISpriteInstance {},
	WeaponHand: class extends self.ISpriteInstance {},
	RosterArray: class extends self.IArrayInstance {},
	Grenade: class extends self.ISpriteInstance {},
	GrenadeRadius: class extends self.ISpriteInstance {},
	PlayerShadow: class extends self.ISpriteInstance {},
	MuzzleFlash: class extends self.ISpriteInstance {},
	AirstrikeRadius: class extends self.ISpriteInstance {},
	BottleRadius: class extends self.ISpriteInstance {},
	FlameBottle: class extends self.ISpriteInstance {},
	CharacterDescription: class extends self.ISpriteFontInstance {},
	Cursor: class extends self.ISpriteInstance {},
	EnemiesLeft: class extends self.ISpriteFontInstance {},
	TimerFont: class extends self.ISpriteFontInstance {},
	TimeHud: class extends self.ISpriteInstance {},
	EraName: class extends self.ISpriteInstance {},
	Reference: class extends self.ISpriteInstance {},
	TitleButton: class extends self.ISpriteFontInstance {},
	CharacterLeft: class extends self.ISpriteFontInstance {},
	ScoreText: class extends self.ISpriteFontInstance {},
	ChooseEra: class extends self.ISpriteInstance {},
	CharacterText: class extends self.IWorldInstance {},
	PlayerDamageBar: class extends self.ITiledBackgroundInstance {},
	PlayerHPBar: class extends self.ITiledBackgroundInstance {},
	PlayerHUD: class extends self.ISpriteInstance {},
	PlayerName: class extends self.ISpriteInstance {},
	EnterScore: class extends self.ISpriteFontInstance {},
	EnterNameText: class extends self.ISpriteFontInstance {},
	EnemyIcon: class extends self.ISpriteInstance {},
	SpecialBar: class extends self.ITiledBackgroundInstance {},
	SpecialHUD: class extends self.ISpriteInstance {},
	TimeParadox: class extends self.ISpriteInstance {},
	AttackName: class extends self.ISpriteFontInstance {},
	EraClear: class extends self.ISpriteInstance {},
	Enemy: class extends self.ISpriteInstance {},
	EnemyMarker: class extends self.ISpriteInstance {},
	Crawler: class extends self.ISpriteInstance {},
	CrawlerSprite: class extends self.ISpriteInstance {},
	EnemyBullet: class extends self.ISpriteInstance {},
	FlyEnemy: class extends self.ISpriteInstance {},
	FlyShadow: class extends self.ISpriteInstance {},
	FlyTarget: class extends self.ISpriteInstance {},
	Tick: class extends self.ISpriteInstance {},
	TickShadow: class extends self.ISpriteInstance {},
	TickTarget: class extends self.ISpriteInstance {},
	EnemyBulletShadow: class extends self.ISpriteInstance {},
	ChaserSprite: class extends self.ISpriteInstance {},
	FeatureKreep: class extends self.ISpriteInstance {},
	FeatureKreepLogo: class extends self.ISpriteInstance {},
	IntroClockHand: class extends self.ISpriteInstance {},
	GameLogo: class extends self.ISpriteInstance {},
	IntroPortal: class extends self.ISpriteInstance {},
	IntroStar: class extends self.ISpriteInstance {},
	LogoBottom: class extends self.ISpriteInstance {},
	LogoShine: class extends self.ISpriteInstance {},
	SelectionBar: class extends self.ISpriteInstance {},
	IntroImage: class extends self.ISpriteInstance {},
	IntroText: class extends self.ISpriteFontInstance {},
	PrimalBackground: class extends self.ITiledBackgroundInstance {},
	Box: class extends self.ISpriteInstance {},
	ExampleBG: class extends self.ISpriteInstance {},
	Portal: class extends self.ISpriteInstance {},
	PortalParticles: class extends self.IParticlesInstance {},
	SwitchEffect: class extends self.IParticlesInstance {},
	LayerDarken: class extends self.ITiledBackgroundInstance {},
	Tilemap: class extends self.ITilemapInstance {},
	BoxOutline: class extends self.ISpriteInstance {},
	ReferenceSprite: class extends self.ISpriteInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	TransitionSprite: class extends self.ISpriteInstance {},
	GameOver: class extends self.ISpriteInstance {},
	GateButton: class extends self.ISpriteInstance {},
	Gate: class extends self.ISpriteInstance {},
	OpenButton: class extends self.ISpriteInstance {},
	ShootOrb: class extends self.ISpriteInstance {},
	Hourglass: class extends self.ISpriteInstance {},
	HelpSign: class extends self.ISpriteInstance {},
	ChaserOutline: class extends self.ISpriteInstance {},
	NoGoZone: class extends self.ISpriteInstance {},
	BulletHit: class extends self.ISpriteInstance {},
	Explosion: class extends self.IParticlesInstance {},
	ExplosionParticle: class extends self.ISpriteInstance {},
	EnemyExplosion: class extends self.ISpriteInstance {},
	RunParticles: class extends self.IParticlesInstance {},
	Fire: class extends self.ISpriteInstance {},
	PlayerCharacters: class extends self.ISpriteInstance {},
	SortY: class extends self.ISpriteInstance {},
	Enemies: class extends self.ISpriteInstance {},
	CrawlerBodies: class extends self.ISpriteInstance {}
}