const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.AJAX,
		C3.Plugins.XML,
		C3.Plugins.Audio,
		C3.Plugins.Arr,
		C3.Plugins.TiledBg,
		C3.Behaviors.Tween,
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Rotate,
		C3.Plugins.Particles,
		C3.Behaviors.Timer,
		C3.Behaviors.EightDir,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Behaviors.MoveTo,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Behaviors.Turret,
		C3.Behaviors.Flash,
		C3.Behaviors.Pathfinding,
		C3.Behaviors.Pin,
		C3.Behaviors.Follow,
		C3.Behaviors.Orbit,
		C3.Behaviors.Fade,
		C3.Behaviors.solid,
		C3.Plugins.Tilemap,
		C3.Plugins.Mouse.Cnds.OnAnyClick,
		C3.Plugins.Keyboard.Cnds.OnAnyKey,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Exps.ImageWidth,
		C3.Plugins.Sprite.Exps.ImageHeight,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetEffect,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Behaviors.EightDir.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Behaviors.EightDir.Exps.MovingAngle,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.MoveTo.Cnds.IsMoving,
		C3.Behaviors.EightDir.Acts.SetMaxSpeed,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.TiledBg.Acts.SetPosToObject,
		C3.Plugins.TiledBg.Acts.MoveToTop,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.System.Acts.SubVar,
		C3.Behaviors.Tween.Acts.StopTweens,
		C3.Behaviors.MoveTo.Acts.SetMaxSpeed,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.TiledBg.Acts.SetVisible,
		C3.Plugins.System.Exps.find,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Mouse.Acts.SetCursor,
		C3.Plugins.Mouse.Cnds.IsButtonDown,
		C3.Behaviors.Rotate.Acts.SetEnabled,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.System.Exps.random,
		C3.Behaviors.Bullet.Exps.AngleOfMotion,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Behaviors.Bullet.Cnds.CompareTravelled,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Timer.Cnds.IsTimerRunning,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Acts.SetObjectTimescale,
		C3.Plugins.System.Exps.int,
		C3.Behaviors.Timer.Exps.CurrentTime,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Behaviors.Orbit.Acts.SetRadius,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Behaviors.Flash.Cnds.IsFlashing,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Behaviors.EightDir.Acts.SetIgnoreInput,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Behaviors.Orbit.Acts.SetEnabled,
		C3.Behaviors.Orbit.Acts.SetOffsetAngle,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Spritefont2.Acts.SetSize,
		C3.Plugins.Spritefont2.Acts.SetVAlign,
		C3.Plugins.Spritefont2.Acts.SetInstanceVar,
		C3.Plugins.System.Exps.replace,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Spritefont2.Acts.TypewriterText,
		C3.Plugins.System.Exps.len,
		C3.Plugins.Spritefont2.Acts.MoveToTop,
		C3.Plugins.Spritefont2.Cnds.OnTypewriterTextFinished,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.Spritefont2.Acts.SetBoolInstanceVar,
		C3.Plugins.Spritefont2.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Spritefont2.Acts.AppendText,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Exps.left,
		C3.Plugins.Spritefont2.Exps.Text,
		C3.Plugins.Spritefont2.Acts.Destroy,
		C3.Plugins.Audio.Acts.RemoveEffects,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Spritefont2.Cnds.IsRunningTypewriterText,
		C3.Plugins.Spritefont2.Acts.TypewriterFinish,
		C3.Plugins.Sprite.Cnds.OnFrameChanged,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Tilemap.Cnds.CompareTileAt,
		C3.Plugins.Tilemap.Exps.TileToPositionX,
		C3.Plugins.Tilemap.Exps.TileToPositionY,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Bullet.Acts.SetAcceleration,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Behaviors.Bullet.Cnds.CompareSpeed,
		C3.Behaviors.Bullet.Cnds.IsEnabled,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.System.Exps.canvastolayerx,
		C3.Plugins.System.Exps.layertocanvasx,
		C3.Plugins.System.Exps.layertocanvasy,
		C3.Plugins.System.Exps.canvastolayery,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Plugins.Arr.Acts.Shuffle,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Audio.Acts.AddFilterEffect,
		C3.Behaviors.Sin.Acts.SetPhase,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.System.Exps.uppercase,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Arr.Acts.Delete,
		C3.Behaviors.Orbit.Acts.Pin,
		C3.Plugins.Sprite.Exps.Count,
		C3.Behaviors.Orbit.Acts.SetRotation,
		C3.Plugins.TiledBg.Acts.SetHeight,
		C3.Plugins.TiledBg.Acts.SetDefaultColor,
		C3.Plugins.System.Exps.rgbex255,
		C3.Plugins.Particles.Acts.SetDefaultColor,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.System.Acts.CreateObjectByName,
		C3.Behaviors.Pathfinding.Acts.RegenerateRegion,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Behaviors.Pathfinding.Cnds.OnPathFound,
		C3.Behaviors.MoveTo.Acts.MoveAlongPathfindingPath,
		C3.Behaviors.Pathfinding.Acts.Stop,
		C3.Behaviors.Pathfinding.Acts.FindPath,
		C3.Plugins.Sprite.Cnds.PickParent,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Behaviors.Follow.Acts.FollowObject,
		C3.Behaviors.Follow.Acts.SetDelay,
		C3.Plugins.Sprite.Acts.MoveForward,
		C3.Behaviors.Follow.Acts.SetPaused,
		C3.Plugins.System.Acts.SortZOrderByInstVar,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Behaviors.Turret.Acts.AcquireTarget,
		C3.Behaviors.Turret.Acts.SetEnabled,
		C3.Plugins.System.Exps.max,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.Spritefont2.Cnds.OnCreated,
		C3.Plugins.Sprite.Exps.Opacity,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Mouse.Acts.SetCursor2,
		C3.Plugins.Spritefont2.Exps.X,
		C3.Plugins.Spritefont2.Exps.TextWidth,
		C3.Plugins.Spritefont2.Exps.Y,
		C3.Plugins.Keyboard.Exps.TypedKey,
		C3.Plugins.Keyboard.Exps.StringFromKeyCode,
		C3.Plugins.Keyboard.Exps.LastKeyCode,
		C3.Plugins.Spritefont2.Cnds.PickParent,
		C3.Plugins.Spritefont2.Acts.SetPosToObject,
		C3.Plugins.Spritefont2.Acts.SetDefaultColor,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Behaviors.Sin.Acts.SetPeriod
	];
};
self.C3_JsPropNameTable = [
	{Keyboard: 0},
	{Mouse: 0},
	{AJAX: 0},
	{XML: 0},
	{Audio: 0},
	{EnterNameArray: 0},
	{Perks: 0},
	{StageTexts: 0},
	{Tween: 0},
	{ExpBar: 0},
	{HealthBar: 0},
	{Shake: 0},
	{Shake2: 0},
	{HUD: 0},
	{StartHUD: 0},
	{StartText: 0},
	{AnatomyFigure: 0},
	{Order: 0},
	{Text: 0},
	{Sine: 0},
	{Hover: 0},
	{Boon: 0},
	{Letter: 0},
	{BonusLetter: 0},
	{Name: 0},
	{PillNum: 0},
	{BonusPill: 0},
	{ChooseMutation: 0},
	{CellPercentage: 0},
	{Rotate: 0},
	{Cursor: 0},
	{Sine2: 0},
	{HealthHUD: 0},
	{HPBarBG: 0},
	{HPParticles: 0},
	{HPParticles2: 0},
	{MagnifyGlass: 0},
	{MagnifyLens: 0},
	{PercentHUD: 0},
	{PerkText: 0},
	{Timer: 0},
	{BarkButton: 0},
	{InfectionIcon: 0},
	{Transition: 0},
	{StageName: 0},
	{Countdown: 0},
	{PerfectMessage: 0},
	{BonusLetterGet: 0},
	{KillCount: 0},
	{BossBar: 0},
	{"8Direction": 0},
	{ScrollTo: 0},
	{BoundToLayout: 0},
	{MoveTo: 0},
	{Player: 0},
	{PlayerShadow: 0},
	{Bullet: 0},
	{DestroyOutsideLayout: 0},
	{Turret: 0},
	{Flash: 0},
	{TankBottom: 0},
	{TankBottomAfterImage: 0},
	{TankGun: 0},
	{TankGunAfterImage: 0},
	{DashBar: 0},
	{DashHUD: 0},
	{DashLoadBar: 0},
	{Defense: 0},
	{ShieldBarrier: 0},
	{SplitBullet: 0},
	{EnemyShot: 0},
	{Slow: 0},
	{Confused: 0},
	{HP: 0},
	{Pathfinding: 0},
	{Blob: 0},
	{EnemySpawnPoint: 0},
	{VirusSprite: 0},
	{Pin: 0},
	{EyeVirus: 0},
	{EyeVirusBody: 0},
	{BodyNum: 0},
	{BodyOrder: 0},
	{Follow: 0},
	{CrawlerSprite: 0},
	{EnemyEgg: 0},
	{Crawler: 0},
	{WormBody: 0},
	{WormSprite: 0},
	{Ready: 0},
	{Exploder: 0},
	{Virus: 0},
	{BossCrawler: 0},
	{WriteText: 0},
	{EnterName: 0},
	{FeatureKreep: 0},
	{FeatureKreepLogo: 0},
	{Uppercase: 0},
	{FunctionKey: 0},
	{KeyboardSprite: 0},
	{Finished: 0},
	{StageText: 0},
	{Content: 0},
	{KeyLetter: 0},
	{EnterKey: 0},
	{IntroTable: 0},
	{TypeCursor: 0},
	{DogPicture: 0},
	{IntroMonitor: 0},
	{IntroTank: 0},
	{SystemMessage: 0},
	{BulletShadow: 0},
	{BulletTrail: 0},
	{Orbit: 0},
	{DestroyEffect: 0},
	{BulletHit: 0},
	{Experience: 0},
	{InfectionPercentage: 0},
	{MuzzleFlash: 0},
	{StarEffect: 0},
	{Fade: 0},
	{PlayerTracks: 0},
	{SplitShadow: 0},
	{Solid: 0},
	{InfectedCell: 0},
	{InfectedCellOutline: 0},
	{FloorBG: 0},
	{OuterTilemap: 0},
	{CellTilemap: 0},
	{Bubble: 0},
	{ExploderSprite: 0},
	{TransitionSquare: 0},
	{OrbitalNum: 0},
	{Orbital: 0},
	{GameLogo: 0},
	{TitleLifeline: 0},
	{LifelineSpot: 0},
	{SkipButton: 0},
	{GameLogo2: 0},
	{PressStart: 0},
	{ToxicCreep: 0},
	{IntroRoom: 0},
	{DogIcon: 0},
	{SpaceReload: 0},
	{GameOver: 0},
	{BossSprite: 0},
	{DogIntroImage: 0},
	{IntroMan: 0},
	{Tombstone: 0},
	{Line: 0},
	{TombstoneName: 0},
	{ExplosionRadius: 0},
	{Sprite: 0},
	{EnterCursor: 0},
	{ZOrder: 0},
	{Tank: 0},
	{StatusTimer: 0},
	{Enemies: 0},
	{EnemyTarget: 0},
	{CrawlerBodies: 0},
	{WormBodies: 0},
	{EnemySprites: 0},
	{GameState: 0},
	{Orbitals: 0},
	{MoveSpeed: 0},
	{Dashes: 0},
	{BarkTimer: 0},
	{Perfect: 0},
	{MaxHP: 0},
	{CellCount: 0},
	{CellsDestroyed: 0},
	{Type: 0},
	{PlayerExp: 0},
	{NextExp: 0},
	{RandomPerk: 0},
	{RandomUpgrade: 0},
	{PerkName: 0},
	{BonusLetters: 0},
	{SpawnTime: 0},
	{EnemyHP: 0},
	{EnemyDestroyed: 0},
	{EnemyKillRequired: 0},
	{PlayerDamage: 0},
	{ShootStream: 0},
	{BulletSpeed: 0},
	{Range: 0},
	{Accuracy: 0},
	{Luck: 0},
	{BulletSize: 0},
	{CritChance: 0},
	{FireRate: 0},
	{BulletEffect: 0},
	{BulletUID: 0},
	{IntroLine: 0},
	{ScreenState: 0},
	{DogName: 0}
];

self.InstanceType = {
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	XML: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	EnterNameArray: class extends self.IArrayInstance {},
	Perks: class extends self.IArrayInstance {},
	StageTexts: class extends self.IArrayInstance {},
	ExpBar: class extends self.ITiledBackgroundInstance {},
	HealthBar: class extends self.ITiledBackgroundInstance {},
	HUD: class extends self.ISpriteInstance {},
	StartHUD: class extends self.ITiledBackgroundInstance {},
	StartText: class extends self.ISpriteFontInstance {},
	AnatomyFigure: class extends self.ISpriteInstance {},
	Boon: class extends self.ISpriteInstance {},
	BonusLetter: class extends self.ISpriteInstance {},
	BonusPill: class extends self.ISpriteInstance {},
	ChooseMutation: class extends self.ISpriteInstance {},
	CellPercentage: class extends self.ISpriteFontInstance {},
	Cursor: class extends self.ISpriteInstance {},
	HealthHUD: class extends self.ISpriteInstance {},
	HPBarBG: class extends self.ISpriteInstance {},
	HPParticles: class extends self.IParticlesInstance {},
	HPParticles2: class extends self.IParticlesInstance {},
	MagnifyGlass: class extends self.ISpriteInstance {},
	MagnifyLens: class extends self.ISpriteInstance {},
	PercentHUD: class extends self.ISpriteInstance {},
	PerkText: class extends self.ISpriteFontInstance {},
	BarkButton: class extends self.ISpriteInstance {},
	InfectionIcon: class extends self.ITiledBackgroundInstance {},
	Transition: class extends self.ISpriteInstance {},
	StageName: class extends self.ISpriteInstance {},
	Countdown: class extends self.ISpriteInstance {},
	PerfectMessage: class extends self.ISpriteInstance {},
	BonusLetterGet: class extends self.ISpriteInstance {},
	KillCount: class extends self.ISpriteFontInstance {},
	BossBar: class extends self.ITiledBackgroundInstance {},
	Player: class extends self.ISpriteInstance {},
	PlayerShadow: class extends self.ISpriteInstance {},
	Bullet: class extends self.ISpriteInstance {},
	TankBottom: class extends self.ISpriteInstance {},
	TankBottomAfterImage: class extends self.ISpriteInstance {},
	TankGun: class extends self.ISpriteInstance {},
	TankGunAfterImage: class extends self.ISpriteInstance {},
	DashBar: class extends self.ITiledBackgroundInstance {},
	DashHUD: class extends self.ISpriteInstance {},
	DashLoadBar: class extends self.ITiledBackgroundInstance {},
	ShieldBarrier: class extends self.ISpriteInstance {},
	SplitBullet: class extends self.ISpriteInstance {},
	EnemyShot: class extends self.ISpriteInstance {},
	Blob: class extends self.ISpriteInstance {},
	EnemySpawnPoint: class extends self.ISpriteInstance {},
	VirusSprite: class extends self.ISpriteInstance {},
	EyeVirus: class extends self.ISpriteInstance {},
	EyeVirusBody: class extends self.ISpriteInstance {},
	CrawlerSprite: class extends self.ISpriteInstance {},
	EnemyEgg: class extends self.ISpriteInstance {},
	Crawler: class extends self.ISpriteInstance {},
	WormBody: class extends self.ISpriteInstance {},
	WormSprite: class extends self.ISpriteInstance {},
	Exploder: class extends self.ISpriteInstance {},
	Virus: class extends self.ISpriteInstance {},
	BossCrawler: class extends self.ISpriteInstance {},
	EnterName: class extends self.ISpriteFontInstance {},
	FeatureKreep: class extends self.ISpriteInstance {},
	FeatureKreepLogo: class extends self.ISpriteInstance {},
	FunctionKey: class extends self.ISpriteInstance {},
	KeyboardSprite: class extends self.ISpriteInstance {},
	StageText: class extends self.ISpriteFontInstance {},
	KeyLetter: class extends self.ISpriteFontInstance {},
	EnterKey: class extends self.ISpriteInstance {},
	IntroTable: class extends self.ITiledBackgroundInstance {},
	TypeCursor: class extends self.ISpriteInstance {},
	DogPicture: class extends self.ISpriteInstance {},
	IntroMonitor: class extends self.ISpriteInstance {},
	IntroTank: class extends self.ISpriteInstance {},
	SystemMessage: class extends self.ISpriteFontInstance {},
	BulletShadow: class extends self.ISpriteInstance {},
	BulletTrail: class extends self.ISpriteInstance {},
	DestroyEffect: class extends self.ISpriteInstance {},
	BulletHit: class extends self.ISpriteInstance {},
	Experience: class extends self.ISpriteInstance {},
	InfectionPercentage: class extends self.ISpriteFontInstance {},
	MuzzleFlash: class extends self.ISpriteInstance {},
	StarEffect: class extends self.ISpriteInstance {},
	PlayerTracks: class extends self.ISpriteInstance {},
	SplitShadow: class extends self.ISpriteInstance {},
	InfectedCell: class extends self.ISpriteInstance {},
	InfectedCellOutline: class extends self.ISpriteInstance {},
	FloorBG: class extends self.ITiledBackgroundInstance {},
	OuterTilemap: class extends self.ITilemapInstance {},
	CellTilemap: class extends self.ITilemapInstance {},
	Bubble: class extends self.ISpriteInstance {},
	ExploderSprite: class extends self.ISpriteInstance {},
	TransitionSquare: class extends self.ISpriteInstance {},
	Orbital: class extends self.ISpriteInstance {},
	GameLogo: class extends self.ISpriteInstance {},
	TitleLifeline: class extends self.ISpriteInstance {},
	LifelineSpot: class extends self.ISpriteInstance {},
	SkipButton: class extends self.ISpriteInstance {},
	GameLogo2: class extends self.ISpriteInstance {},
	PressStart: class extends self.ISpriteInstance {},
	ToxicCreep: class extends self.ISpriteInstance {},
	IntroRoom: class extends self.ISpriteInstance {},
	DogIcon: class extends self.ISpriteInstance {},
	SpaceReload: class extends self.ITiledBackgroundInstance {},
	GameOver: class extends self.ISpriteInstance {},
	BossSprite: class extends self.ISpriteInstance {},
	DogIntroImage: class extends self.ISpriteInstance {},
	IntroMan: class extends self.ISpriteInstance {},
	Tombstone: class extends self.ISpriteInstance {},
	TombstoneName: class extends self.ISpriteFontInstance {},
	ExplosionRadius: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	EnterCursor: class extends self.ISpriteInstance {},
	ZOrder: class extends self.ISpriteInstance {},
	Tank: class extends self.ISpriteInstance {},
	Enemies: class extends self.ISpriteInstance {},
	EnemyTarget: class extends self.ISpriteInstance {},
	CrawlerBodies: class extends self.ISpriteInstance {},
	WormBodies: class extends self.ISpriteInstance {},
	EnemySprites: class extends self.ISpriteInstance {}
}